/* Embedded Bootstrap admin console (single-page app). The HTML is stored
 * inline so the console is served directly from the epsilond binary with no
 * external files; only the Bootstrap stylesheet/script load from a CDN. */

#include "admin_console.h"

#include <stdlib.h>
#include <string.h>

static const char console_html[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>EpsilonDB Admin</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n"
    "<style>\n"
    "body{font-size:.95rem}\n"
    ".wrap{max-width:1240px}\n"
    "table{font-size:.875rem}\n"
    "pre{max-height:420px;overflow:auto}\n"
    ".zt-table{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.8rem}\n"
    ".zt-table td,.zt-table th{white-space:pre}\n"
    ".zt-null{font-style:italic;font-weight:300;color:#6c757d}\n"
    ".tab-active{background:#0d6efd;color:#fff}\n"
    "</style>\n"
    "</head>\n"
    "<body class=\"bg-body-tertiary\">\n"
    "<div id=\"auth-view\" class=\"d-none\">\n"
    "  <div class=\"container wrap mt-5\">\n"
    "    <div class=\"row justify-content-center\">\n"
    "      <div class=\"col-md-5\">\n"
    "        <div class=\"card shadow-sm\">\n"
    "          <div class=\"card-body p-4\">\n"
    "            <h4 class=\"mb-1\">EpsilonDB Admin</h4>\n"
    "            <p id=\"auth-subtitle\" class=\"text-muted mb-4\"></p>\n"
    "            <div id=\"auth-form\"></div>\n"
    "            <div id=\"auth-error\" class=\"text-danger small mt-2\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div id=\"app-view\" class=\"d-none\">\n"
    "  <nav class=\"navbar navbar-expand-lg bg-primary-subtle border-bottom\">\n"
    "    <div class=\"container-fluid wrap\">\n"
    "      <span class=\"navbar-brand fw-semibold\">EpsilonDB</span>\n"
    "      <div class=\"ms-auto d-flex align-items-center gap-2\">\n"
    "        <span id=\"whoami\" class=\"text-muted small\"></span>\n"
    "        <button class=\"btn btn-sm btn-outline-secondary\" onclick=\"logout()\">Log out</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </nav>\n"
    "  <div class=\"container-fluid wrap mt-3\">\n"
    "    <div class=\"row\">\n"
    "      <div class=\"col-md-2\">\n"
    "        <div id=\"section-nav\" class=\"nav nav-pills flex-column gap-1 small\"></div>\n"
    "      </div>\n"
    "      <div class=\"col-md-10\">\n"
    "        <div id=\"content\"></div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"modal fade\" id=\"confirm-modal\" tabindex=\"-1\">\n"
    "  <div class=\"modal-dialog\"><div class=\"modal-content\">\n"
    "    <div class=\"modal-header\"><h5 class=\"modal-title\">Confirm delete</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button></div>\n"
    "    <div class=\"modal-body\" id=\"confirm-message\"></div>\n"
    "    <div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button><button type=\"button\" class=\"btn btn-danger\" onclick=\"confirmYes()\">Delete</button></div>\n"
    "  </div></div>\n"
    "</div>\n"
    "<div class=\"modal fade\" id=\"user-modal\" tabindex=\"-1\">\n"
    "  <div class=\"modal-dialog\"><div class=\"modal-content\">\n"
    "    <div class=\"modal-header\"><h5 class=\"modal-title\" id=\"user-modal-title\">User groups</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button></div>\n"
    "    <div class=\"modal-body\">\n"
    "      <label class=\"form-label\">Username</label><input id=\"um-name\" class=\"form-control mb-2\">\n"
    "      <label class=\"form-label\">Groups (Ctrl/Cmd+click for multiple)</label><select id=\"um-groups\" class=\"form-select\" multiple size=\"5\"></select>\n"
    "    </div>\n"
    "    <div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button><button type=\"button\" class=\"btn btn-primary\" onclick=\"saveUserGroups()\">Save</button></div>\n"
    "  </div></div>\n"
    "</div>\n"
    "<div class=\"modal fade\" id=\"partition-modal\" tabindex=\"-1\">\n"
    "  <div class=\"modal-dialog modal-lg\"><div class=\"modal-content\">\n"
    "    <div class=\"modal-header\"><h5 class=\"modal-title\" id=\"partition-modal-title\">Partition</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button></div>\n"
    "    <div class=\"modal-body\">\n"
    "      <div class=\"row g-2 mb-3\">\n"
    "        <div class=\"col\"><label class=\"form-label\">Database</label><select id=\"pm-db\" class=\"form-select\"></select></div>\n"
    "        <div class=\"col\"><label class=\"form-label\">Partition name</label><input id=\"pm-name\" class=\"form-control\"></div>\n"
    "      </div>\n"
    "      <p class=\"text-muted small\">No boxes checked for a permission = allow all groups.</p>\n"
    "      <div class=\"row\">\n"
    "        <div class=\"col\"><h6>Create</h6><div id=\"pm-create\"></div></div>\n"
    "        <div class=\"col\"><h6>Update</h6><div id=\"pm-update\"></div></div>\n"
    "        <div class=\"col\"><h6>Read</h6><div id=\"pm-read\"></div></div>\n"
    "        <div class=\"col\"><h6>Delete</h6><div id=\"pm-delete\"></div></div>\n"
    "      </div>\n"
    "      <hr>\n"
    "      <h6>SQLite tuning</h6>\n"
    "      <div class=\"row g-2\">\n"
    "        <div class=\"col\"><label class=\"form-label small mb-1\">Journal mode</label><select id=\"pm-journal\" class=\"form-select\"><option>DELETE</option><option selected>TRUNCATE</option><option>WAL</option></select></div>\n"
    "        <div class=\"col\"><label class=\"form-label small mb-1\">Cache size (KB; 0 = default)</label><input id=\"pm-cache\" class=\"form-control\" type=\"number\" value=\"0\"></div>\n"
    "        <div class=\"col\"><label class=\"form-label small mb-1\">VACUUM (seconds)</label><input id=\"pm-vacuum\" class=\"form-control\" type=\"number\" value=\"21600\"></div>\n"
    "        <div class=\"col\"><label class=\"form-label small mb-1\">REINDEX (seconds)</label><input id=\"pm-reindex\" class=\"form-control\" type=\"number\" value=\"3600\"></div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button><button type=\"button\" class=\"btn btn-primary\" onclick=\"savePartition()\">Save</button></div>\n"
    "  </div></div>\n"
    "</div>\n"
    "<div class=\"modal fade\" id=\"record-modal\" tabindex=\"-1\">\n"
    "  <div class=\"modal-dialog modal-lg modal-dialog-scrollable\"><div class=\"modal-content\">\n"
    "    <div class=\"modal-header\"><h5 class=\"modal-title\" id=\"record-modal-title\">Edit record</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button></div>\n"
    "    <div class=\"modal-body\">\n"
    "      <label class=\"form-label small mb-1\">Id</label>\n"
    "      <input id=\"rm-id\" class=\"form-control font-monospace mb-2\" readonly>\n"
    "      <label class=\"form-label small mb-1\">Document (JSON)</label>\n"
    "      <textarea id=\"rm-doc\" class=\"form-control font-monospace\" rows=\"14\" spellcheck=\"false\"></textarea>\n"
    "      <div id=\"rm-err\" class=\"text-danger small mt-2\"></div>\n"
    "    </div>\n"
    "    <div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button><button type=\"button\" class=\"btn btn-primary\" onclick=\"saveRecord()\">Save</button></div>\n"
    "  </div></div>\n"
    "</div>\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js\"></script>\n"
    "<script>\n"
    "var state = { token: localStorage.getItem('edb_token') || '', user: '' };\n"
    "var SECTIONS = [\n"
    "  ['overview','Overview'], ['databases','Databases'], ['groups','Groups'],\n"
    "  ['users','Users'], ['partitions','Partitions'], ['keyspaces','Keyspaces'],\n"
    "  ['settings','Settings'], ['data','Data'], ['analytics','Analytics'], ['benchmark','Benchmark'], ['cluster','Cluster']\n"
    "];\n"
    "function api(method, path, body) {\n"
    "  var headers = {};\n"
    "  if (state.token) headers['Authorization'] = 'Bearer ' + state.token;\n"
    "  var init = { method: method, headers: headers };\n"
    "  if (body !== undefined && body !== null) { headers['Content-Type'] = 'application/json'; init.body = JSON.stringify(body); }\n"
    "  return fetch(path, init).then(function (r) {\n"
    "    return r.text().then(function (t) {\n"
    "      var j = null; try { j = t ? JSON.parse(t) : null; } catch (e) {}\n"
    "      return { status: r.status, json: j, text: t };\n"
    "    });\n"
    "  });\n"
    "}\n"
    "function show(which) {\n"
    "  document.getElementById('auth-view').classList.toggle('d-none', which !== 'auth');\n"
    "  document.getElementById('app-view').classList.toggle('d-none', which !== 'app');\n"
    "}\n"
    "function setError(msg) { document.getElementById('auth-error').textContent = msg || ''; }\n"
    "var rows_cache = {};\n"
    "var dt_mode = 'table';\n"
    "var dt_last = null;\n"
    "var dt_pending = null;\n"
    "var confirm_cb = null;\n"
    "function confirmDelete(message, cb) {\n"
    "  document.getElementById('confirm-message').textContent = message;\n"
    "  confirm_cb = cb;\n"
    "  bootstrap.Modal.getOrCreateInstance(document.getElementById('confirm-modal')).show();\n"
    "}\n"
    "function confirmYes() {\n"
    "  var cb = confirm_cb; confirm_cb = null;\n"
    "  bootstrap.Modal.getInstance(document.getElementById('confirm-modal')).hide();\n"
    "  if (cb) cb();\n"
    "}\n"
    "var partition_editing = false;\n"
    "function loadGroups(cb) {\n"
    "  api('GET', '/admin/groups').then(function (r) {\n"
    "    rows_cache.groups = r.json || [];\n"
    "    cb();\n"
    "  });\n"
    "}\n"
    "function groupBitNum(g) { return Number(g.bit_position) - 1; }\n"
    "function groupsFromMask(maskStr, allGroups) {\n"
    "  var m; try { m = BigInt(maskStr || '0'); } catch (e) { m = 0n; }\n"
    "  return (allGroups || []).filter(function (g) { return (m & (1n << BigInt(groupBitNum(g)))) !== 0n; });\n"
    "}\n"
    "function maskFromSelected(selId) {\n"
    "  var sel = document.getElementById(selId); var m = 0n;\n"
    "  for (var i = 0; i < sel.options.length; i++) { if (sel.options[i].selected) m |= 1n << BigInt(Number(sel.options[i].value)); }\n"
    "  return m.toString();\n"
    "}\n"
    "function fillGroupSelect(selId, groups) {\n"
    "  document.getElementById(selId).innerHTML = (groups || []).map(function (g) {\n"
    "    return '<option value=\"' + groupBitNum(g) + '\">' + esc(g.name) + '</option>';\n"
    "  }).join('');\n"
    "}\n"
    "function renderGroupChecks(containerId, groups, maskStr) {\n"
    "  var m; try { m = BigInt(maskStr || '0'); } catch (e) { m = 0n; }\n"
    "  document.getElementById(containerId).innerHTML = (groups && groups.length ? groups.map(function (g) {\n"
    "    var bit = groupBitNum(g);\n"
    "    var checked = (m & (1n << BigInt(bit))) !== 0n;\n"
    "    return '<div class=\"form-check\"><input class=\"form-check-input\" type=\"checkbox\" value=\"' + bit + '\"' + (checked ? ' checked' : '') + '><label class=\"form-check-label\">' + esc(g.name) + '</label></div>';\n"
    "  }).join('') : '<div class=\"text-muted small\">No groups defined</div>');\n"
    "}\n"
    "function checksToMask(containerId) {\n"
    "  var m = 0n;\n"
    "  document.querySelectorAll('#' + containerId + ' input:checked').forEach(function (c) { m |= 1n << BigInt(Number(c.value)); });\n"
    "  return m.toString();\n"
    "}\n"
    "function fillDatabaseSelect(selId, selected) {\n"
    "  api('GET', '/admin/databases').then(function (r) {\n"
    "    document.getElementById(selId).innerHTML = '<option value=\"\">database…</option>' + (r.json || []).map(function (d) {\n"
    "      return '<option' + (selected === d.name ? ' selected' : '') + '>' + esc(d.name) + '</option>';\n"
    "    }).join('');\n"
    "  });\n"
    "}\n"
    "function renderWelcome() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Welcome to EpsilonDB';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<div class=\"d-grid gap-2\">' +\n"
    "    '<button class=\"btn btn-primary btn-lg\" onclick=\"renderSetup()\">Start new cluster</button>' +\n"
    "    '<button class=\"btn btn-outline-primary btn-lg\" onclick=\"renderJoin()\">Join a cluster</button>' +\n"
    "    '</div>' +\n"
    "    '<p class=\"text-muted small mt-3\">Start new cluster makes this node the seed and creates the admin account. Join a cluster connects to an existing node and adopts its users and data.</p>';\n"
    "}\n"
    "function renderSetup() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'First run: create the administrator account';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Username</label>' +\n"
    "    '<input id=\"a-user\" class=\"form-control mb-2\" value=\"admin\">' +\n"
    "    '<label class=\"form-label\">Password</label>' +\n"
    "    '<input id=\"a-pass\" type=\"password\" class=\"form-control mb-2\">' +\n"
    "    '<label class=\"form-label\">Cluster secret (optional: encrypts the mesh; joiners must enter it)</label>' +\n"
    "    '<input id=\"a-secret\" type=\"password\" class=\"form-control mb-3\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doSetup()\">Create admin</button>' +\n"
    "    '<button class=\"btn btn-link w-100 mt-2\" onclick=\"renderWelcome()\">Back</button>';\n"
    "}\n"
    "function renderLogin() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Sign in to continue';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Username</label>' +\n"
    "    '<input id=\"a-user\" class=\"form-control mb-2\" autocomplete=\"username\">' +\n"
    "    '<label class=\"form-label\">Password</label>' +\n"
    "    '<input id=\"a-pass\" type=\"password\" class=\"form-control mb-3\" autocomplete=\"current-password\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doLogin()\">Sign in</button>';\n"
    "}\n"
    "function renderJoin() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Join an existing cluster';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Seed address</label>' +\n"
    "    '<input id=\"join-addr\" class=\"form-control mb-2\" value=\"127.0.0.1\">' +\n"
    "    '<label class=\"form-label\">Seed peer port (-n)</label>' +\n"
    "    '<input id=\"join-port\" type=\"number\" class=\"form-control mb-2\">' +\n"
    "    '<label class=\"form-label\">Cluster secret (if the cluster has one)</label>' +\n"
    "    '<input id=\"join-secret\" type=\"password\" class=\"form-control mb-3\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doJoin()\">Join cluster</button>' +\n"
    "    '<button class=\"btn btn-link w-100 mt-2\" onclick=\"renderWelcome()\">Back</button>';\n"
    "}\n"
    "function doJoin() {\n"
    "  var addr = document.getElementById('join-addr').value.trim();\n"
    "  var port = parseInt(document.getElementById('join-port').value, 10);\n"
    "  var secret = document.getElementById('join-secret').value;\n"
    "  if (!addr || !port) { setError('Enter a seed address and peer port'); return; }\n"
    "  setError('Joining cluster...');\n"
    "  var body = { addr: addr, port: port };\n"
    "  if (secret) body.secret = secret;\n"
    "  api('POST', '/admin/join', body).then(function (r) {\n"
    "    if (r.status === 200) { checkState(); }\n"
    "    else if (r.status === 409) { setError('A rebalance is in progress; try again shortly'); }\n"
    "    else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function checkState() {\n"
    "  api('GET', '/admin/console/state').then(function (r) {\n"
    "    if (!r.json) { show('auth'); renderLogin(); return; }\n"
    "    if (state.token && r.json.authenticated) { state.user = r.json.username; enterApp(); return; }\n"
    "    if (r.json.setup_required) { show('auth'); renderWelcome(); return; }\n"
    "    show('auth'); renderLogin();\n"
    "  });\n"
    "}\n"
    "function doSetup() {\n"
    "  var u = document.getElementById('a-user').value.trim() || 'admin';\n"
    "  var p = document.getElementById('a-pass').value;\n"
    "  var secret = document.getElementById('a-secret').value;\n"
    "  var body = { username: u, password: p };\n"
    "  if (secret) body.secret = secret;\n"
    "  api('POST', '/admin/setup', body).then(function (r) {\n"
    "    if (r.status === 200 && r.json && r.json.token) {\n"
    "      state.token = r.json.token; state.user = r.json.username;\n"
    "      localStorage.setItem('edb_token', state.token); enterApp();\n"
    "    } else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function doLogin() {\n"
    "  var u = document.getElementById('a-user').value.trim();\n"
    "  var p = document.getElementById('a-pass').value;\n"
    "  api('POST', '/admin/login', { username: u, password: p }).then(function (r) {\n"
    "    if (r.status === 200 && r.json && r.json.token) {\n"
    "      state.token = r.json.token; state.user = r.json.username;\n"
    "      localStorage.setItem('edb_token', state.token); enterApp();\n"
    "    } else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function logout() {\n"
    "  api('POST', '/admin/logout').then(function () {\n"
    "    state.token = ''; state.user = '';\n"
    "    localStorage.removeItem('edb_token');\n"
    "    show('auth'); renderLogin();\n"
    "  });\n"
    "}\n"
    "function failText(r) { return r.json && r.json.error ? r.json.error : ('HTTP ' + r.status); }\n"
    "function enterApp() {\n"
    "  show('app');\n"
    "  document.getElementById('whoami').textContent = 'Signed in as ' + state.user;\n"
    "  renderNav(); load('overview');\n"
    "}\n"
    "function renderNav() {\n"
    "  var nav = document.getElementById('section-nav');\n"
    "  nav.innerHTML = SECTIONS.map(function (s) {\n"
    "    return '<a href=\"#\" data-k=\"' + s[0] + '\" class=\"nav-link\" onclick=\"load(\\'' + s[0] + '\\');return false;\">' + s[1] + '</a>';\n"
    "  }).join('');\n"
    "}\n"
    "function load(key) {\n"
    "  var links = document.querySelectorAll('#section-nav .nav-link');\n"
    "  for (var i = 0; i < links.length; i++) links[i].classList.remove('active');\n"
    "  var lk = document.querySelector('#section-nav [data-k=\\\"' + key + '\\\"]');\n"
    "  if (lk) lk.classList.add('active');\n"
    "  window['render' + key.charAt(0).toUpperCase() + key.slice(1)]();\n"
    "}\n"
    "function table(columns, rows, raw) {\n"
    "  raw = raw || {};\n"
    "  var head = '<tr>' + columns.map(function (c) { return '<th>' + c + '</th>'; }).join('') + '</tr>';\n"
    "  var body = rows.map(function (r) {\n"
    "    return '<tr>' + r.map(function (cell, j) { return '<td>' + (raw[j] ? cell : esc(cell)) + '</td>'; }).join('') + '</tr>';\n"
    "  }).join('');\n"
    "  return '<table class=\"table table-striped table-bordered align-middle\"><thead>' + head + '</thead><tbody>' + body + '</tbody></table>';\n"
    "}\n"
    "function esc(s) { return String(s === undefined || s === null ? '' : s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\\\"/g,'&quot;'); }\n"
    "function err(msg) { return '<div class=\"alert alert-danger\">' + esc(msg) + '</div>'; }\n"
    "function ok(msg) { return '<div class=\"alert alert-success\">' + esc(msg) + '</div>'; }\n"
    "function renderOverview() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/status').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    c.innerHTML =\n"
    "      '<h5>Overview</h5>' +\n"
    "      '<dl class=\"row\">' +\n"
    "      '<dt class=\"col-sm-3\">Service</dt><dd class=\"col-sm-9\">' + esc(r.json.service) + '</dd>' +\n"
    "      '<dt class=\"col-sm-3\">Version</dt><dd class=\"col-sm-9\">' + esc(r.json.version) + '</dd>' +\n"
    "      '</dl>';\n"
    "  });\n"
    "}\n"
    "function renderDatabases() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Databases</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/databases').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    rows_cache.databases = r.json;\n"
    "    var rows = r.json.map(function (d, i) { return [d.name, d.replication_factor, '<button class=\"btn btn-sm btn-danger\" onclick=\"delDb(' + i + ')\">Delete</button>']; });\n"
    "    c.innerHTML = table(['Name', 'Replication factor', ''], rows, {2:true}) +\n"
    "      '<div class=\"card mt-3\"><div class=\"card-body\"><h6>Create database</h6>' +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"db-name\" class=\"form-control\" placeholder=\"name\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"db-rf\" class=\"form-control\" type=\"number\" value=\"1\" min=\"1\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createDb()\">Create</button></div></div></div></div>';\n"
    "  });\n"
    "}\n"
    "function createDb() { mutate('POST', '/admin/databases', { name: id('db-name'), replication_factor: parseInt(id('db-rf'), 10) }, renderDatabases); }\n"
    "function delDb(i) {\n"
    "  var d = rows_cache.databases[i];\n"
    "  confirmDelete('Delete database \"' + d.name + '\"?', function () {\n"
    "    api('DELETE', '/admin/databases/' + encodeURIComponent(d.name)).then(renderDatabases);\n"
    "  });\n"
    "}\n"
    "function renderGroups() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Groups</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/groups').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    rows_cache.groups = r.json;\n"
    "    var rows = r.json.map(function (g, i) { return [g.name, g.bit_position, '<button class=\"btn btn-sm btn-danger\" onclick=\"delGroup(' + i + ')\">Delete</button>']; });\n"
    "    c.innerHTML = table(['Name', 'Bit', ''], rows, {2:true}) +\n"
    "      '<div class=\"card mt-3\"><div class=\"card-body\"><h6>Create group</h6>' +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"grp-name\" class=\"form-control\" placeholder=\"group name\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createGroup()\">Create</button></div></div></div></div>';\n"
    "  });\n"
    "}\n"
    "function createGroup() { mutate('POST', '/admin/groups', { name: id('grp-name') }, renderGroups); }\n"
    "function delGroup(i) {\n"
    "  var g = rows_cache.groups[i];\n"
    "  confirmDelete('Delete group \"' + g.name + '\"?', function () {\n"
    "    api('DELETE', '/admin/groups/' + encodeURIComponent(g.name)).then(renderGroups);\n"
    "  });\n"
    "}\n"
    "function renderUsers() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Users</h5><div class=\"spinner-border\"></div>';\n"
    "  loadGroups(function () {\n"
    "    api('GET', '/admin/users').then(function (r) {\n"
    "      if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "      rows_cache.users = r.json;\n"
    "      var all = rows_cache.groups || [];\n"
    "      var rows = r.json.map(function (u, i) {\n"
    "        var names = groupsFromMask(u.groups, all).map(function (g) { return g.name; }).join(', ') || '(none)';\n"
    "        return [u.name, names,\n"
    "          '<button class=\"btn btn-sm btn-outline-primary\" onclick=\"editUser(' + i + ')\">Edit groups</button> ' +\n"
    "          '<button class=\"btn btn-sm btn-danger\" onclick=\"delUser(' + i + ')\">Delete</button>'];\n"
    "      });\n"
    "      c.innerHTML = table(['Name', 'Groups', ''], rows, {2:true}) +\n"
    "        '<div class=\"card mt-3\"><div class=\"card-body\"><h6>Create user</h6>' +\n"
    "        '<div class=\"row g-2\"><div class=\"col\"><input id=\"usr-name\" class=\"form-control\" placeholder=\"username\"></div>' +\n"
    "        '<div class=\"col\"><input id=\"usr-pass\" type=\"password\" class=\"form-control\" placeholder=\"password (optional)\"></div>' +\n"
    "        '<div class=\"col\"><select id=\"usr-groups\" class=\"form-select\" multiple size=\"4\"></select></div>' +\n"
    "        '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createUser()\">Create</button></div></div>' +\n"
    "        '<div class=\"text-muted small mt-1\">Ctrl/Cmd+click to select multiple groups</div></div></div>';\n"
    "      fillGroupSelect('usr-groups', all);\n"
    "    });\n"
    "  });\n"
    "}\n"
    "function createUser() {\n"
    "  var body = { name: id('usr-name').trim(), groups: maskFromSelected('usr-groups') };\n"
    "  var pw = document.getElementById('usr-pass').value;\n"
    "  if (pw) { body.password = pw; }\n"
    "  mutate('POST', '/admin/users', body, renderUsers);\n"
    "}\n"
    "function editUser(i) {\n"
    "  var u = rows_cache.users[i];\n"
    "  document.getElementById('user-modal-title').textContent = 'Groups for ' + u.name;\n"
    "  document.getElementById('um-name').value = u.name;\n"
    "  fillGroupSelect('um-groups', rows_cache.groups || []);\n"
    "  var m; try { m = BigInt(u.groups || '0'); } catch (e) { m = 0n; }\n"
    "  var sel = document.getElementById('um-groups');\n"
    "  for (var k = 0; k < sel.options.length; k++) { sel.options[k].selected = (m & (1n << BigInt(Number(sel.options[k].value)))) !== 0n; }\n"
    "  bootstrap.Modal.getOrCreateInstance(document.getElementById('user-modal')).show();\n"
    "}\n"
    "function saveUserGroups() {\n"
    "  var name = document.getElementById('um-name').value.trim();\n"
    "  var groups = maskFromSelected('um-groups');\n"
    "  api('PUT', '/admin/users', { name: name, groups: groups }).then(function (r) {\n"
    "    bootstrap.Modal.getInstance(document.getElementById('user-modal')).hide();\n"
    "    renderUsers();\n"
    "  });\n"
    "}\n"
    "function delUser(i) {\n"
    "  var u = rows_cache.users[i];\n"
    "  confirmDelete('Delete user \"' + u.name + '\"?', function () {\n"
    "    api('DELETE', '/admin/users/' + encodeURIComponent(u.name)).then(renderUsers);\n"
    "  });\n"
    "}\n"
    "function renderPartitions() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Partitions</h5><div class=\"spinner-border\"></div>';\n"
    "  loadGroups(function () {\n"
    "    api('GET', '/admin/partitions').then(function (r) {\n"
    "      if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "      rows_cache.partitions = r.json;\n"
    "      var rows = r.json.map(function (p, i) {\n"
    "        return [p.database, p.name, p.create_mask, p.update_mask, p.read_mask, p.delete_mask,\n"
    "          p.journal_mode, p.cache_size || 'default', p.vacuum_seconds, p.reindex_seconds,\n"
    "          '<button class=\"btn btn-sm btn-outline-primary\" onclick=\"editPart(' + i + ')\">Edit</button> ' +\n"
    "          '<button class=\"btn btn-sm btn-danger\" onclick=\"delPart(' + i + ')\">Delete</button>'];\n"
    "      });\n"
    "      c.innerHTML = table(['Database', 'Name', 'Create', 'Update', 'Read', 'Delete', 'Journal', 'Cache (KB)', 'VACUUM (s)', 'REINDEX (s)', ''], rows, {10:true}) +\n"
    "        '<button class=\"btn btn-primary mt-2\" onclick=\"newPartition()\">Create partition</button>';\n"
    "    });\n"
    "  });\n"
    "}\n"
    "function setPartitionTuning(p) {\n"
    "  document.getElementById('pm-journal').value = (p && p.journal_mode) || 'TRUNCATE';\n"
    "  document.getElementById('pm-cache').value = (p && p.cache_size !== undefined) ? p.cache_size : 0;\n"
    "  document.getElementById('pm-vacuum').value = (p && p.vacuum_seconds !== undefined) ? p.vacuum_seconds : 21600;\n"
    "  document.getElementById('pm-reindex').value = (p && p.reindex_seconds !== undefined) ? p.reindex_seconds : 3600;\n"
    "}\n"
    "function newPartition() {\n"
    "  partition_editing = false;\n"
    "  document.getElementById('partition-modal-title').textContent = 'Create partition';\n"
    "  document.getElementById('pm-name').value = '';\n"
    "  document.getElementById('pm-db').disabled = false;\n"
    "  fillDatabaseSelect('pm-db', '');\n"
    "  setPartitionTuning(null);\n"
    "  var g = rows_cache.groups || [];\n"
    "  renderGroupChecks('pm-create', g, '0');\n"
    "  renderGroupChecks('pm-update', g, '0');\n"
    "  renderGroupChecks('pm-read', g, '0');\n"
    "  renderGroupChecks('pm-delete', g, '0');\n"
    "  bootstrap.Modal.getOrCreateInstance(document.getElementById('partition-modal')).show();\n"
    "}\n"
    "function editPart(i) {\n"
    "  var p = rows_cache.partitions[i];\n"
    "  partition_editing = true;\n"
    "  document.getElementById('partition-modal-title').textContent = 'Edit partition ' + p.database + '/' + p.name;\n"
    "  document.getElementById('pm-name').value = p.name;\n"
    "  document.getElementById('pm-db').disabled = true;\n"
    "  fillDatabaseSelect('pm-db', p.database);\n"
    "  setPartitionTuning(p);\n"
    "  var g = rows_cache.groups || [];\n"
    "  renderGroupChecks('pm-create', g, p.create_mask);\n"
    "  renderGroupChecks('pm-update', g, p.update_mask);\n"
    "  renderGroupChecks('pm-read', g, p.read_mask);\n"
    "  renderGroupChecks('pm-delete', g, p.delete_mask);\n"
    "  bootstrap.Modal.getOrCreateInstance(document.getElementById('partition-modal')).show();\n"
    "}\n"
    "function savePartition() {\n"
    "  var db = id('pm-db');\n"
    "  var name = id('pm-name').trim();\n"
    "  if (!db || !name) { return; }\n"
    "  var body = { database: db, name: name,\n"
    "    create_mask: checksToMask('pm-create'),\n"
    "    update_mask: checksToMask('pm-update'),\n"
    "    read_mask: checksToMask('pm-read'),\n"
    "    delete_mask: checksToMask('pm-delete'),\n"
    "    journal_mode: id('pm-journal'),\n"
    "    cache_size: parseInt(id('pm-cache'), 10) || 0,\n"
    "    vacuum_seconds: parseInt(id('pm-vacuum'), 10) || 0,\n"
    "    reindex_seconds: parseInt(id('pm-reindex'), 10) || 0 };\n"
    "  api(partition_editing ? 'PUT' : 'POST', '/admin/partitions', body).then(function (r) {\n"
    "    bootstrap.Modal.getInstance(document.getElementById('partition-modal')).hide();\n"
    "    renderPartitions();\n"
    "  });\n"
    "}\n"
    "function delPart(i) {\n"
    "  var p = rows_cache.partitions[i];\n"
    "  confirmDelete('Delete partition \"' + p.database + '/' + p.name + '\"?', function () {\n"
    "    api('DELETE', '/admin/partitions/' + encodeURIComponent(p.database) + '/' + encodeURIComponent(p.name)).then(renderPartitions);\n"
    "  });\n"
    "}\n"
    "function renderKeyspaces() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Keyspaces</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/keyspaces').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    rows_cache.keyspaces = r.json;\n"
    "    var rows = r.json.map(function (k, i) { return [k.database,\n"
    "      '<a href=\"#\" onclick=\"gotoKeyspace(' + i + ', false); return false;\">' + esc(k.partition) + '</a>',\n"
    "      '<a href=\"#\" onclick=\"gotoKeyspace(' + i + ', true); return false;\">' + esc(k.name) + '</a>']; });\n"
    "    c.innerHTML = table(['Database', 'Partition', 'Keyspace'], rows, {1:true, 2:true});\n"
    "  });\n"
    "}\n"
    "function gotoKeyspace(i, withKs) {\n"
    "  var k = rows_cache.keyspaces[i];\n"
    "  if (!k) return;\n"
    "  gotoDataQuery(k.database, k.partition, withKs ? k.name : '');\n"
    "}\n"
    "function gotoDataQuery(db, part, ks) {\n"
    "  dt_pending = { db: db, part: part, ks: ks || '' };\n"
    "  load('data');\n"
    "}\n"
    "function renderSettings() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Settings</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/settings').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    rows_cache.settings = r.json;\n"
    "    var rows = r.json.map(function (s, i) { return [s.name, JSON.stringify(s.value), '<button class=\"btn btn-sm btn-danger\" onclick=\"delSetting(' + i + ')\">Delete</button>']; });\n"
    "    c.innerHTML = table(['Name', 'Value', ''], rows, {2:true}) +\n"
    "      '<div class=\"card mt-3\"><div class=\"card-body\"><h6>Set setting</h6>' +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"set-name\" class=\"form-control\" placeholder=\"setting name\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"set-val\" class=\"form-control\" placeholder=\"JSON value\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"setSetting()\">Set</button></div></div></div></div>';\n"
    "  });\n"
    "}\n"
    "function setSetting() {\n"
    "  var v = id('set-val'); var body = v; try { body = JSON.parse(v); } catch (e) {}\n"
    "  mutate('POST', '/admin/settings/' + id('set-name'), body, renderSettings);\n"
    "}\n"
    "function delSetting(i) {\n"
    "  var s = rows_cache.settings[i];\n"
    "  confirmDelete('Delete setting \"' + s.name + '\"?', function () {\n"
    "    api('DELETE', '/admin/settings/' + encodeURIComponent(s.name)).then(renderSettings);\n"
    "  });\n"
    "}\n"
    "function renderData() {\n"
    "  document.getElementById('content').innerHTML =\n"
    "    '<h5>Data</h5>' +\n"
    "    '<div class=\"row g-2 mb-2 align-items-end\">' +\n"
    "    '<div class=\"col-2\"><label class=\"form-label small mb-1\">Operation</label><select id=\"dt-op\" class=\"form-select\" onchange=\"opChanged()\"><option value=\"get\">get</option><option value=\"put\">put</option><option value=\"rm\">rm</option><option value=\"all\">all</option><option value=\"ids\">ids</option><option value=\"query\">query</option></select></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Database</label><select id=\"dt-db\" class=\"form-select\" onchange=\"loadParts()\"><option value=\"\">database…</option></select></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Partition</label><select id=\"dt-part\" class=\"form-select\" onchange=\"partChanged()\"><option value=\"\">partition…</option></select><input id=\"dt-part-new\" class=\"form-control mt-1\" placeholder=\"new partition\" style=\"display:none\"></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\" id=\"dt-ks-label\">Keyspace</label><select id=\"dt-ks\" class=\"form-select\" onchange=\"ksChanged()\"><option value=\"\">keyspace…</option></select><input id=\"dt-ks-new\" class=\"form-control mt-1\" placeholder=\"new keyspace\" style=\"display:none\"></div>' +\n"
    "    '<div class=\"col-2\" id=\"dt-id-wrap\"><label class=\"form-label small mb-1\">Id (get/put/rm)</label><input id=\"dt-id\" class=\"form-control\"></div>' +\n"
    "    '<div class=\"col-auto\"><button class=\"btn btn-primary mb-1\" onclick=\"dataOp()\">Run</button></div></div>' +\n"
    "    '<div id=\"dt-filter-wrap\" class=\"mb-2\" style=\"display:none\">' +\n"
    "      '<div class=\"d-flex align-items-center mb-1\">' +\n"
    "        '<span class=\"fw-semibold small me-2\">Filters (AND)</span>' +\n"
    "        '<button type=\"button\" class=\"btn btn-sm btn-outline-primary\" onclick=\"addFilterRow()\">Add filter</button>' +\n"
    "      '</div>' +\n"
    "      '<div id=\"dt-filters\"></div>' +\n"
    "    '</div>' +\n"
    "    '<textarea id=\"dt-body\" class=\"form-control mb-2\" rows=\"4\" placeholder=\"put document (JSON)\" style=\"display:none\"></textarea>' +\n"
    "    '<div class=\"d-flex align-items-center mb-1\">' +\n"
    "      '<span class=\"fw-semibold small me-2\">View</span>' +\n"
    "      '<div class=\"btn-group btn-group-sm\" role=\"group\">' +\n"
    "        '<button type=\"button\" class=\"btn btn-outline-secondary active\" id=\"dt-mode-table\" data-mode=\"table\" onclick=\"setDtMode(this)\">Table</button>' +\n"
    "        '<button type=\"button\" class=\"btn btn-outline-secondary\" id=\"dt-mode-json\" data-mode=\"json\" onclick=\"setDtMode(this)\">JSON</button>' +\n"
    "      '</div>' +\n"
    "    '</div>' +\n"
    "    '<div id=\"dt-out\"></div>';\n"
    "  loadDbs();\n"
    "}\n"
    "function loadDbs() {\n"
    "  api('GET', '/admin/databases').then(function (r) {\n"
    "    document.getElementById('dt-db').innerHTML = '<option value=\"\">database…</option>' +\n"
    "      (r.json || []).map(function (d) { return '<option>' + esc(d.name) + '</option>'; }).join('');\n"
    "    if (dt_pending) {\n"
    "      document.getElementById('dt-db').value = dt_pending.db;\n"
    "      if (id('dt-db') !== dt_pending.db) { dt_pending = null; return; }\n"
    "      loadParts();\n"
    "    }\n"
    "  });\n"
    "}\n"
    "function resetSelect(selId, placeholder) {\n"
    "  document.getElementById(selId).innerHTML = '<option value=\"\">' + placeholder + '</option>';\n"
    "}\n"
    "function loadParts() {\n"
    "  var db = id('dt-db');\n"
    "  resetSelect('dt-part', 'partition…'); resetSelect('dt-ks', 'keyspace…');\n"
    "  document.getElementById('dt-part-new').style.display = 'none';\n"
    "  document.getElementById('dt-ks-new').style.display = 'none';\n"
    "  if (!db) return;\n"
    "  api('GET', '/admin/keyspaces?database=' + encodeURIComponent(db)).then(function (r) {\n"
    "    var seen = {};\n"
    "    var opts = (r.json || []).map(function (k) {\n"
    "      if (seen[k.partition]) return ''; seen[k.partition] = 1;\n"
    "      return '<option>' + esc(k.partition) + '</option>';\n"
    "    }).join('');\n"
    "    document.getElementById('dt-part').innerHTML = '<option value=\"\">partition…</option>' + opts + '<option value=\"__new__\">(new…)</option>';\n"
    "    if (dt_pending) {\n"
    "      document.getElementById('dt-part').value = dt_pending.part;\n"
    "      if (id('dt-part') !== dt_pending.part) { dt_pending = null; return; }\n"
    "      loadKss();\n"
    "    }\n"
    "  });\n"
    "}\n"
    "function partChanged() {\n"
    "  document.getElementById('dt-part-new').style.display = id('dt-part') === '__new__' ? '' : 'none';\n"
    "  loadKss();\n"
    "}\n"
    "function loadKss() {\n"
    "  var db = id('dt-db'); var part = id('dt-part');\n"
    "  resetSelect('dt-ks', 'keyspace…');\n"
    "  document.getElementById('dt-ks-new').style.display = 'none';\n"
    "  if (!db || !part) return;\n"
    "  if (part === '__new__') {\n"
    "    document.getElementById('dt-ks').innerHTML = '<option value=\"\">keyspace…</option><option value=\"__new__\">(new…)</option>';\n"
    "    if (dt_pending) { finishPendingDataQuery(); }\n"
    "    return;\n"
    "  }\n"
    "  api('GET', '/admin/keyspaces?database=' + encodeURIComponent(db)).then(function (r) {\n"
    "    document.getElementById('dt-ks').innerHTML = '<option value=\"\">keyspace…</option>' +\n"
    "      (r.json || []).filter(function (k) { return k.partition === part; }).map(function (k) { return '<option>' + esc(k.name) + '</option>'; }).join('') +\n"
    "      '<option value=\"__new__\">(new…)</option>';\n"
    "    if (dt_pending) { finishPendingDataQuery(); }\n"
    "  });\n"
    "}\n"
    "function finishPendingDataQuery() {\n"
    "  var p = dt_pending; dt_pending = null;\n"
    "  document.getElementById('dt-ks').value = p.ks;\n"
    "  ksChanged();\n"
    "  document.getElementById('dt-op').value = 'query';\n"
    "  opChanged();\n"
    "  dataOp();\n"
    "}\n"
    "function ksChanged() {\n"
    "  document.getElementById('dt-ks-new').style.display = id('dt-ks') === '__new__' ? '' : 'none';\n"
    "}\n"
    "function resolveOrNew(selId, newId) {\n"
    "  var v = id(selId);\n"
    "  return v === '__new__' ? document.getElementById(newId).value.trim() : v;\n"
    "}\n"
    "function dataOp() {\n"
    "  var op = id('dt-op');\n"
    "  var db = id('dt-db');\n"
    "  var part = resolveOrNew('dt-part', 'dt-part-new');\n"
    "  var ks = resolveOrNew('dt-ks', 'dt-ks-new');\n"
    "  var recId = id('dt-id').trim();\n"
    "  var loc = { db: db, part: part, ks: ks };\n"
    "  var out = document.getElementById('dt-out');\n"
    "  if (!db || !part) { out.textContent = 'Select a database and partition'; return; }\n"
    "  if (op === 'query' && !ks) {\n"
    "    api('POST', '/data/' + encodeURIComponent(db) + '/' + encodeURIComponent(part) + '/query', { filters: collectFilters() }).then(function (r) { showData(r, op, recId, loc); });\n"
    "    return;\n"
    "  }\n"
    "  if (!ks) { out.textContent = 'Select a keyspace'; return; }\n"
    "  var base = '/data/' + encodeURIComponent(db) + '/' + encodeURIComponent(part) + '/' + encodeURIComponent(ks);\n"
    "  if (op === 'get') { api('GET', base + '/' + encodeURIComponent(recId)).then(function (r) { showData(r, op, recId, loc); }); }\n"
    "  else if (op === 'rm') { api('DELETE', base + '/' + encodeURIComponent(recId)).then(function (r) { showData(r, op, recId, loc); }); }\n"
    "  else if (op === 'put') {\n"
    "    var raw = document.getElementById('dt-body').value.trim();\n"
    "    var doc; try { doc = raw ? JSON.parse(raw) : undefined; } catch (e) { out.textContent = 'Document is not valid JSON'; return; }\n"
    "    api('PUT', base + '/' + encodeURIComponent(recId), doc).then(function (r) { showData(r, op, recId, loc); });\n"
    "  }\n"
    "  else { api('POST', base + '/' + op, { filters: collectFilters() }).then(function (r) { showData(r, op, recId, loc); }); }\n"
    "}\n"
    "function dataCellText(v) {\n"
    "  if (v === null || v === undefined) return '';\n"
    "  if (typeof v === 'string') return v;\n"
    "  if (typeof v === 'number') return String(v);\n"
    "  if (typeof v === 'boolean') return v ? 'true' : 'false';\n"
    "  return JSON.stringify(v);\n"
    "}\n"
    "function renderDataTable(json, keyForSingle, loc) {\n"
    "  var rows = json;\n"
    "  if (rows && !Array.isArray(rows) && typeof rows === 'object') {\n"
    "    var single = {};\n"
    "    if (keyForSingle) single.id = keyForSingle;\n"
    "    Object.keys(rows).forEach(function (k) { if (k !== 'id') single[k] = rows[k]; });\n"
    "    rows = [single];\n"
    "  }\n"
    "  if (!Array.isArray(rows)) {\n"
    "    return '<pre class=\"bg-light border rounded p-2\">' + esc(json === null || json === undefined ? '' : JSON.stringify(json, null, 2)) + '</pre>';\n"
    "  }\n"
    "  if (rows.length === 0) return '<div class=\"text-muted small\">(empty)</div>';\n"
    "  var isScalarList = rows[0] === null || typeof rows[0] !== 'object';\n"
    "  if (isScalarList) {\n"
    "    return '<table class=\"table table-bordered table-sm zt-table\"><thead><tr><th>id</th></tr></thead><tbody>' +\n"
    "      rows.map(function (v) { return '<tr><td>' + idCell(loc, v) + '</td></tr>'; }).join('') + '</tbody></table>';\n"
    "  }\n"
    "  var cols = [];\n"
    "  rows.forEach(function (row) { Object.keys(row).forEach(function (k) { if (cols.indexOf(k) === -1) cols.push(k); }); });\n"
    "  var head = '<tr>' + cols.map(function (c) { return '<th>' + esc(c) + '</th>'; }).join('') + '</tr>';\n"
    "  var body = rows.map(function (row) {\n"
    "    return '<tr>' + cols.map(function (c) {\n"
    "      if (!Object.prototype.hasOwnProperty.call(row, c)) return '<td></td>';\n"
    "      var v = row[c];\n"
    "      if (v === null) return '<td class=\"zt-null\">null</td>';\n"
    "      if (c === 'id') return '<td>' + idCell(loc, v) + '</td>';\n"
    "      return '<td>' + esc(dataCellText(v)) + '</td>';\n"
    "    }).join('') + '</tr>';\n"
    "  }).join('');\n"
    "  return '<div class=\"table-responsive\"><table class=\"table table-bordered table-sm zt-table align-top\"><thead>' + head + '</thead><tbody>' + body + '</tbody></table></div>';\n"
    "}\n"
    "function idCell(loc, v) {\n"
    "  if (!loc || !loc.ks) return esc(dataCellText(v));\n"
    "  return '<a href=\"#\" onclick=\"editRecord(' + esc(JSON.stringify({ db: loc.db, part: loc.part, ks: loc.ks, id: String(v) })) + '); return false;\">' + esc(dataCellText(v)) + '</a>';\n"
    "}\n"
    "var record_loc = null;\n"
    "function dataPath(loc) {\n"
    "  return '/data/' + encodeURIComponent(loc.db) + '/' + encodeURIComponent(loc.part) + '/' + encodeURIComponent(loc.ks) + '/' + encodeURIComponent(loc.id);\n"
    "}\n"
    "function editRecord(loc) {\n"
    "  record_loc = loc;\n"
    "  document.getElementById('rm-id').value = loc.id;\n"
    "  document.getElementById('rm-err').textContent = '';\n"
    "  document.getElementById('record-modal-title').textContent = 'Edit record: ' + loc.db + '/' + loc.part + '/' + loc.ks + '/' + loc.id;\n"
    "  document.getElementById('rm-doc').value = '';\n"
    "  api('GET', dataPath(loc)).then(function (r) {\n"
    "    if (r.status >= 400 || !r.json || typeof r.json !== 'object') {\n"
    "      document.getElementById('rm-err').textContent = failText(r);\n"
    "      return;\n"
    "    }\n"
    "    document.getElementById('rm-doc').value = JSON.stringify(r.json, null, 2);\n"
    "    bootstrap.Modal.getOrCreateInstance(document.getElementById('record-modal')).show();\n"
    "  });\n"
    "}\n"
    "function saveRecord() {\n"
    "  var raw = document.getElementById('rm-doc').value.trim();\n"
    "  var doc;\n"
    "  try { doc = raw ? JSON.parse(raw) : {}; } catch (e) { document.getElementById('rm-err').textContent = 'Document is not valid JSON'; return; }\n"
    "  var btn = document.querySelector('#record-modal .btn-primary');\n"
    "  btn.disabled = true;\n"
    "  api('PUT', dataPath(record_loc), doc).then(function (r) {\n"
    "    btn.disabled = false;\n"
    "    if (r.status >= 400) { document.getElementById('rm-err').textContent = failText(r); return; }\n"
    "    bootstrap.Modal.getInstance(document.getElementById('record-modal')).hide();\n"
    "    dataOp();\n"
    "  });\n"
    "}\n"
    "function setDtMode(btn) {\n"
    "  dt_mode = btn.dataset.mode;\n"
    "  document.getElementById('dt-mode-table').classList.toggle('active', dt_mode === 'table');\n"
    "  document.getElementById('dt-mode-json').classList.toggle('active', dt_mode === 'json');\n"
    "  if (dt_last) renderDtResult(dt_last);\n"
    "}\n"
    "function jsonView(r) {\n"
    "  return '<pre class=\"bg-light border rounded p-2\">' + esc(r.json !== null ? JSON.stringify(r.json, null, 2) : r.text) + '</pre>';\n"
    "}\n"
    "function renderDtResult(last) {\n"
    "  var r = last.r; var op = last.op; var recId = last.recId;\n"
    "  var out = document.getElementById('dt-out');\n"
    "  if (r.status >= 400) { out.innerHTML = err(failText(r)); return; }\n"
    "  if (dt_mode === 'json') { out.innerHTML = jsonView(r); return; }\n"
    "  if (op === 'get' || op === 'all' || op === 'ids' || op === 'query') {\n"
    "    out.innerHTML = renderDataTable(r.json, op === 'get' ? recId : undefined, last.loc);\n"
    "  } else {\n"
    "    out.innerHTML = jsonView(r);\n"
    "  }\n"
    "}\n"
    "function showData(r, op, recId, loc) {\n"
    "  dt_last = { r: r, op: op, recId: recId, loc: loc || null };\n"
    "  renderDtResult(dt_last);\n"
    "}\n"
    "function opChanged() {\n"
    "  var op = id('dt-op');\n"
    "  var isRead = op === 'query' || op === 'all' || op === 'ids';\n"
    "  var isRecord = op === 'get' || op === 'put' || op === 'rm';\n"
    "  document.getElementById('dt-filter-wrap').style.display = isRead ? '' : 'none';\n"
    "  document.getElementById('dt-body').style.display = op === 'put' ? '' : 'none';\n"
    "  document.getElementById('dt-id-wrap').style.display = isRecord ? '' : 'none';\n"
    "  document.getElementById('dt-ks-label').textContent = op === 'query' ? 'Keyspace (optional)' : 'Keyspace';\n"
    "}\n"
    "function addFilterRow() {\n"
    "  var div = document.createElement('div');\n"
    "  div.className = 'filter-row row g-2 mb-2 align-items-center';\n"
    "  div.innerHTML =\n"
    "    '<div class=\"col\"><input class=\"form-control form-control-sm f-key\" placeholder=\"key (dotted ok)\"></div>' +\n"
    "    '<div class=\"col-2\"><select class=\"form-select form-select-sm f-op\"><option>eq</option><option>ne</option><option>gt</option><option>gte</option><option>lt</option><option>lte</option></select></div>' +\n"
    "    '<div class=\"col\"><input class=\"form-control form-control-sm f-val\" placeholder=\"value\"></div>' +\n"
    "    '<div class=\"col-2\"><select class=\"form-select form-select-sm f-type\"><option value=\"auto\">auto</option><option value=\"string\">string</option><option value=\"number\">number</option><option value=\"boolean\">boolean</option></select></div>' +\n"
    "    '<div class=\"col-auto\"><button type=\"button\" class=\"btn btn-sm btn-outline-danger\" onclick=\"removeFilterRow(this)\">&times;</button></div>';\n"
    "  document.getElementById('dt-filters').appendChild(div);\n"
    "}\n"
    "function removeFilterRow(btn) {\n"
    "  var row = btn.closest('.filter-row');\n"
    "  if (row) row.remove();\n"
    "}\n"
    "function parseFilterValue(text, type) {\n"
    "  if (type === 'string') return text;\n"
    "  if (type === 'boolean') return text === 'true';\n"
    "  if (type === 'number') { var n = Number(text); return isFinite(n) ? n : 0; }\n"
    "  if (text === 'true') return true;\n"
    "  if (text === 'false') return false;\n"
    "  if (text === 'null') return null;\n"
    "  if (text !== '' && isFinite(Number(text))) return Number(text);\n"
    "  return text;\n"
    "}\n"
    "function collectFilters() {\n"
    "  var rows = document.querySelectorAll('#dt-filters .filter-row');\n"
    "  var out = [];\n"
    "  for (var i = 0; i < rows.length; i++) {\n"
    "    var key = rows[i].querySelector('.f-key').value.trim();\n"
    "    var op = rows[i].querySelector('.f-op').value;\n"
    "    var val = rows[i].querySelector('.f-val').value;\n"
    "    var type = rows[i].querySelector('.f-type').value;\n"
    "    if (!key) continue;\n"
    "    out.push({ key: key, operator: op, value: parseFilterValue(val, type) });\n"
    "  }\n"
    "    return out;\n"
    "}\n"
    "function analyticsChart(id, type, labels, datasets, opts) {\n"
    "  var el = document.getElementById(id);\n"
    "  if (!el || !window.Chart) return;\n"
    "  if (window._edb_charts && window._edb_charts[id]) window._edb_charts[id].destroy();\n"
    "  window._edb_charts = window._edb_charts || {};\n"
    "  window._edb_charts[id] = new Chart(el, { type: type, data: { labels: labels, datasets: datasets }, options: opts || {} });\n"
    "}\n"
    "function renderAnalytics() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Analytics</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/analytics').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var d = r.json;\n"
    "    var shards = d.shards || [];\n"
    "    var slow = d.slow || [];\n"
    "    var nodes = d.nodes || [];\n"
    "    var pending = (d.cluster && d.cluster.pending_changes) || 0;\n"
    "    var tot = { reads: 0, writes: 0, updates: 0, deletes: 0, read_us: 0, write_us: 0 };\n"
    "    shards.forEach(function (s) { tot.reads += s.reads; tot.writes += s.writes; tot.updates += s.updates; tot.deletes += s.deletes; tot.read_us += s.read_us; tot.write_us += s.write_us; });\n"
    "    var avgReadMs = tot.reads ? (tot.read_us / tot.reads / 1000).toFixed(2) : 0;\n"
    "    var avgWriteMs = tot.writes ? (tot.write_us / tot.writes / 1000).toFixed(2) : 0;\n"
    "    function card(label, value) { return '<div class=\"col\"><div class=\"card shadow-sm\"><div class=\"card-body py-2\"><div class=\"text-muted small\">' + label + '</div><div class=\"fs-4 fw-semibold\">' + value + '</div></div></div></div>'; }\n"
    "    var html = '<div class=\"row g-2 mb-3\">' +\n"
    "      card('Nodes', nodes.length) + card('Reads', tot.reads) + card('Writes', tot.writes) + card('Updates', tot.updates) + card('Deletes', tot.deletes) + card('Avg read', avgReadMs + ' ms') + card('Avg write', avgWriteMs + ' ms') + card('Pending repl.', pending) +\n"
    "      '</div>';\n"
    "    html += '<div class=\"row g-3\">' +\n"
    "      '<div class=\"col-lg-7\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h6>Reads &amp; writes per shard</h6><canvas id=\"edb-chart-shards\"></canvas></div></div></div>' +\n"
    "      '<div class=\"col-lg-5\"><div class=\"card shadow-sm\"><div class=\"card-body\"><h6>Top 10 slowest operations</h6><canvas id=\"edb-chart-slow\"></canvas></div></div></div>' +\n"
    "      '</div>';\n"
    "    html += '<h6 class=\"mt-4\">Shard workload</h6>';\n"
    "    html += table(['Partition', 'Keyspace', 'Reads', 'Writes', 'Updates', 'Deletes', 'Avg read (ms)', 'Avg write (ms)'], shards.map(function (s) {\n"
    "      return [s.partition, s.keyspace, s.reads, s.writes, s.updates, s.deletes, s.reads ? (s.read_us / s.reads / 1000).toFixed(2) : '0', s.writes ? (s.write_us / s.writes / 1000).toFixed(2) : '0'];\n"
    "    }));\n"
    "    html += '<h6 class=\"mt-4\">Slowest operations</h6>';\n"
    "    html += table(['Type', 'Partition', 'Keyspace', 'Filter key', 'Count', 'Avg (ms)', 'Max (ms)'], slow.map(function (s) {\n"
    "      return [s.kind, s.partition, s.keyspace, s.filter || '(none)', s.count, (s.total_us / s.count / 1000).toFixed(2), (s.max_us / 1000).toFixed(2)];\n"
    "    }));\n"
    "    c.innerHTML = html;\n"
    "    if (shards.length) {\n"
    "      analyticsChart('edb-chart-shards', 'bar', shards.map(function (s) { return s.partition + '/' + s.keyspace; }), [\n"
    "        { label: 'Reads', data: shards.map(function (s) { return s.reads; }), backgroundColor: 'rgba(13,110,253,0.6)' },\n"
    "        { label: 'Writes', data: shards.map(function (s) { return s.writes; }), backgroundColor: 'rgba(25,135,84,0.6)' }\n"
    "      ], { responsive: true });\n"
    "    }\n"
    "    if (slow.length) {\n"
    "      var topSlow = slow.slice().sort(function (a, b) { return b.max_us - a.max_us; }).slice(0, 10);\n"
    "      var kindColour = { read: 'rgba(13,110,253,0.7)', write: 'rgba(25,135,84,0.7)', delete: 'rgba(255,193,7,0.7)', query: 'rgba(220,53,69,0.7)' };\n"
    "      analyticsChart('edb-chart-slow', 'bar', topSlow.map(function (s) { return '[' + s.kind + '] ' + s.partition + '/' + (s.keyspace || '*') + (s.filter ? ' [' + s.filter + ']' : ''); }), [\n"
    "        { label: 'Max (ms)', data: topSlow.map(function (s) { return (s.max_us / 1000).toFixed(2); }), backgroundColor: topSlow.map(function (s) { return kindColour[s.kind] || 'rgba(108,117,125,0.7)'; }) }\n"
    "      ], { indexAxis: 'y', responsive: true });\n"
    "    }\n"
    "  });\n"
    "}\n"
    "function renderBenchmark() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML =\n"
    "    '<h5>Performance benchmark</h5>' +\n"
    "    '<p class=\"text-muted small\">Creates a throwaway database and 10 partitions, times writes / gets / filtered queries / updates / deletes, then deletes everything. Partitions are spread across worker threads so shards are exercised concurrently. This can take a while at the default 100k records.</p>' +\n"
    "    '<div class=\"row g-2 mb-3 align-items-end\">' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Records per partition</label><input id=\"bm-records\" class=\"form-control\" type=\"number\" value=\"100000\"></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Replication factor</label><input id=\"bm-rf\" class=\"form-control\" type=\"number\" value=\"1\"></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Cache size (KB; 0 = default)</label><input id=\"bm-cache\" class=\"form-control\" type=\"number\" value=\"0\"></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Threads (0 = one per partition)</label><input id=\"bm-threads\" class=\"form-control\" type=\"number\" value=\"0\"></div>' +\n"
    "    '<div class=\"col\"><label class=\"form-label small mb-1\">Journal mode</label><select id=\"bm-journal\" class=\"form-select\"><option>DELETE</option><option selected>TRUNCATE</option><option>WAL</option></select></div>' +\n"
    "    '<div class=\"col-auto\"><button id=\"bm-run\" class=\"btn btn-primary\" onclick=\"runBenchmark()\">Run</button></div></div>' +\n"
    "    '<div id=\"bm-out\"></div>';\n"
    "}\n"
    "function runBenchmark() {\n"
    "  var c = document.getElementById('content');\n"
    "  var btn = document.getElementById('bm-run');\n"
    "  btn.disabled = true;\n"
    "  document.getElementById('bm-out').innerHTML = '<div class=\"alert alert-info\">Running benchmark… this may take a minute or more.</div>';\n"
    "  var body = { records: parseInt(id('bm-records'), 10) || 100000,\n"
    "    replication_factor: parseInt(id('bm-rf'), 10) || 1,\n"
    "    cache_size: parseInt(id('bm-cache'), 10) || 0,\n"
    "    threads: parseInt(id('bm-threads'), 10) || 0,\n"
    "    journal_mode: id('bm-journal') };\n"
    "  api('POST', '/admin/benchmark', body).then(function (r) {\n"
    "    btn.disabled = false;\n"
    "    if (r.status >= 400 || !r.json) { document.getElementById('bm-out').innerHTML = err(failText(r)); return; }\n"
    "    var d = r.json;\n"
    "    function row(name, ph) { return [name, ph.count, ph.seconds.toFixed(3), Math.round(ph.ops_per_sec).toLocaleString()]; }\n"
    "    var rows = [row('Writes', d.writes), row('Gets', d.gets), row('Queries', d.queries), row('Updates', d.updates), row('Deletes', d.deletes)];\n"
    "    var html = '<div class=\"alert alert-success\">Benchmark complete (' + d.total_records.toLocaleString() + ' records, ' + d.partitions + ' partitions, RF ' + d.replication_factor + ', cache ' + d.cache_size + ', ' + d.journal_mode + ', ' + d.threads + ' threads). Database deleted.</div>';\n"
    "    html += table(['Operation', 'Count', 'Seconds', 'Ops/sec'], rows);\n"
    "    document.getElementById('bm-out').innerHTML = html;\n"
    "  });\n"
    "}\n"
    "function renderCluster() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Cluster</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/cluster').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var nodes = r.json.nodes || [];\n"
    "    var rows = nodes.map(function (n) {\n"
    "      var status = n.online ? '<span class=\"badge bg-success\">online</span>' : '<span class=\"badge bg-secondary\">offline</span>';\n"
    "      if (n.removed) status += ' <span class=\"badge bg-danger\">removed</span>';\n"
    "      var action = n.removed || r.json.node_id === n.id\n"
    "        ? ''\n"
    "        : '<button class=\"btn btn-sm btn-danger\" onclick=\"removeNode(\\'' + n.id + '\\')\">Remove</button>';\n"
    "      return [n.id, n.addr + ':' + n.port, status, action];\n"
    "    });\n"
    "    c.innerHTML = '<h6>Nodes</h6>' + table(['Node', 'Address', 'Status', ''], rows, {2:true, 3:true}) +\n"
    "      '<h6>Cluster state</h6><pre class=\"bg-light border rounded p-2\">' + esc(JSON.stringify(r.json, null, 2)) + '</pre>' +\n"
    "      '<h6>Join a node</h6><div class=\"row g-2\"><div class=\"col\"><input id=\"join-addr\" class=\"form-control\" placeholder=\"127.0.0.1\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"join-port\" class=\"form-control\" type=\"number\" placeholder=\"port\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"join-secret\" type=\"password\" class=\"form-control\" placeholder=\"cluster secret (optional)\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"joinNode()\">Join</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function joinNode() {\n"
    "  var body = { addr: id('join-addr'), port: parseInt(id('join-port'), 10) };\n"
    "  var secret = document.getElementById('join-secret').value;\n"
    "  if (secret) body.secret = secret;\n"
    "  mutate('POST', '/admin/join', body, renderCluster);\n"
    "}\n"
    "function removeNode(nodeId) {\n"
    "  confirmDelete('Remove node \"' + nodeId + '\" from the cluster? Its ranges will be re-absorbed by the remaining nodes.', function () {\n"
    "    mutate('POST', '/admin/remove-node', { node_id: nodeId }, renderCluster);\n"
    "  });\n"
    "}\n"
    "function id(n) { return document.getElementById(n).value; }\n"
    "function mutate(method, path, body, after) {\n"
    "  api(method, path, body).then(function (r) { after(); });\n"
    "}\n"
    "checkState();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

static bool console_handler(const edb_http_request *req, edb_http_response *res)
{
    (void)req;
    res->status = 200;
    res->content_type = "text/html; charset=utf-8";
    res->body = strdup(console_html);
    res->body_len = strlen(console_html);
    return true;
}

bool edb_admin_console_register(edb_http_server *srv)
{
    if (!srv) {
        return false;
    }
    return edb_http_add_handler(srv, "GET", "/admin", console_handler);
}
