/* Embedded Bootstrap admin console (single-page app). The HTML is stored
 * inline so the console is served directly from the zestyd binary with no
 * external files; only the Bootstrap stylesheet/script load from a CDN. */

#include "admin_console.h"

#include <stdlib.h>
#include <string.h>

static const char console_html[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>ZestyDB Admin</title>\n"
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n"
    "<style>\n"
    "body{font-size:.95rem}\n"
    ".wrap{max-width:1240px}\n"
    "table{font-size:.875rem}\n"
    "pre{max-height:420px;overflow:auto}\n"
    ".tab-active{background:#0d6efd;color:#fff}\n"
    "</style>\n"
    "</head>\n"
    "<body class=\"bg-body-tertiary\">\n"
    "<div id=\"auth-view\" class=\"d-none\">\n"
    "  <div class=\"container wrap mt-5\">\n"
    "    <div class=\"row justify-content-center\">\n"
    "      <div class=\"col-md-5\">\n"
    "        <div class=\"card shadow-sm\">\n"
    "          <div class=\"card-body p-4\">\n"
    "            <h4 class=\"mb-1\">ZestyDB Admin</h4>\n"
    "            <p id=\"auth-subtitle\" class=\"text-muted mb-4\"></p>\n"
    "            <div id=\"auth-form\"></div>\n"
    "            <div id=\"auth-error\" class=\"text-danger small mt-2\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div id=\"app-view\" class=\"d-none\">\n"
    "  <nav class=\"navbar navbar-expand-lg bg-primary-subtle border-bottom\">\n"
    "    <div class=\"container-fluid wrap\">\n"
    "      <span class=\"navbar-brand fw-semibold\">ZestyDB</span>\n"
    "      <div class=\"ms-auto d-flex align-items-center gap-2\">\n"
    "        <span id=\"whoami\" class=\"text-muted small\"></span>\n"
    "        <button class=\"btn btn-sm btn-outline-secondary\" onclick=\"logout()\">Log out</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </nav>\n"
    "  <div class=\"container-fluid wrap mt-3\">\n"
    "    <div class=\"row\">\n"
    "      <div class=\"col-md-2\">\n"
    "        <div id=\"section-nav\" class=\"nav nav-pills flex-column gap-1 small\"></div>\n"
    "      </div>\n"
    "      <div class=\"col-md-10\">\n"
    "        <div id=\"content\"></div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n"
    "<script>\n"
    "var state = { token: localStorage.getItem('zdb_token') || '', user: '' };\n"
    "var SECTIONS = [\n"
    "  ['overview','Overview'], ['databases','Databases'], ['groups','Groups'],\n"
    "  ['users','Users'], ['partitions','Partitions'], ['keyspaces','Keyspaces'],\n"
    "  ['settings','Settings'], ['data','Data'], ['cluster','Cluster']\n"
    "];\n"
    "function api(method, path, body) {\n"
    "  var headers = {};\n"
    "  if (state.token) headers['Authorization'] = 'Bearer ' + state.token;\n"
    "  var init = { method: method, headers: headers };\n"
    "  if (body !== undefined && body !== null) { headers['Content-Type'] = 'application/json'; init.body = JSON.stringify(body); }\n"
    "  return fetch(path, init).then(function (r) {\n"
    "    return r.text().then(function (t) {\n"
    "      var j = null; try { j = t ? JSON.parse(t) : null; } catch (e) {}\n"
    "      return { status: r.status, json: j, text: t };\n"
    "    });\n"
    "  });\n"
    "}\n"
    "function show(which) {\n"
    "  document.getElementById('auth-view').classList.toggle('d-none', which !== 'auth');\n"
    "  document.getElementById('app-view').classList.toggle('d-none', which !== 'app');\n"
    "}\n"
    "function setError(msg) { document.getElementById('auth-error').textContent = msg || ''; }\n"
    "function renderWelcome() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Welcome to ZestyDB';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<div class=\"d-grid gap-2\">' +\n"
    "    '<button class=\"btn btn-primary btn-lg\" onclick=\"renderSetup()\">Start new cluster</button>' +\n"
    "    '<button class=\"btn btn-outline-primary btn-lg\" onclick=\"renderJoin()\">Join a cluster</button>' +\n"
    "    '</div>' +\n"
    "    '<p class=\"text-muted small mt-3\">Start new cluster makes this node the seed and creates the admin account. Join a cluster connects to an existing node and adopts its users and data.</p>';\n"
    "}\n"
    "function renderSetup() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'First run: create the administrator account';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Username</label>' +\n"
    "    '<input id=\"a-user\" class=\"form-control mb-2\" value=\"admin\">' +\n"
    "    '<label class=\"form-label\">Password</label>' +\n"
    "    '<input id=\"a-pass\" type=\"password\" class=\"form-control mb-3\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doSetup()\">Create admin</button>' +\n"
    "    '<button class=\"btn btn-link w-100 mt-2\" onclick=\"renderWelcome()\">Back</button>';\n"
    "}\n"
    "function renderLogin() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Sign in to continue';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Username</label>' +\n"
    "    '<input id=\"a-user\" class=\"form-control mb-2\" autocomplete=\"username\">' +\n"
    "    '<label class=\"form-label\">Password</label>' +\n"
    "    '<input id=\"a-pass\" type=\"password\" class=\"form-control mb-3\" autocomplete=\"current-password\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doLogin()\">Sign in</button>';\n"
    "}\n"
    "function renderJoin() {\n"
    "  setError('');\n"
    "  document.getElementById('auth-subtitle').textContent = 'Join an existing cluster';\n"
    "  document.getElementById('auth-form').innerHTML =\n"
    "    '<label class=\"form-label\">Seed address</label>' +\n"
    "    '<input id=\"join-addr\" class=\"form-control mb-2\" value=\"127.0.0.1\">' +\n"
    "    '<label class=\"form-label\">Seed peer port (-n)</label>' +\n"
    "    '<input id=\"join-port\" type=\"number\" class=\"form-control mb-3\">' +\n"
    "    '<button class=\"btn btn-primary w-100\" onclick=\"doJoin()\">Join cluster</button>' +\n"
    "    '<button class=\"btn btn-link w-100 mt-2\" onclick=\"renderWelcome()\">Back</button>';\n"
    "}\n"
    "function doJoin() {\n"
    "  var addr = document.getElementById('join-addr').value.trim();\n"
    "  var port = parseInt(document.getElementById('join-port').value, 10);\n"
    "  if (!addr || !port) { setError('Enter a seed address and peer port'); return; }\n"
    "  setError('Joining cluster...');\n"
    "  api('POST', '/admin/join', { addr: addr, port: port }).then(function (r) {\n"
    "    if (r.status === 200) { checkState(); }\n"
    "    else if (r.status === 409) { setError('A rebalance is in progress; try again shortly'); }\n"
    "    else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function checkState() {\n"
    "  api('GET', '/admin/console/state').then(function (r) {\n"
    "    if (!r.json) { show('auth'); renderLogin(); return; }\n"
    "    if (state.token && r.json.authenticated) { state.user = r.json.username; enterApp(); return; }\n"
    "    if (r.json.setup_required) { show('auth'); renderWelcome(); return; }\n"
    "    show('auth'); renderLogin();\n"
    "  });\n"
    "}\n"
    "function doSetup() {\n"
    "  var u = document.getElementById('a-user').value.trim() || 'admin';\n"
    "  var p = document.getElementById('a-pass').value;\n"
    "  api('POST', '/admin/setup', { username: u, password: p }).then(function (r) {\n"
    "    if (r.status === 200 && r.json && r.json.token) {\n"
    "      state.token = r.json.token; state.user = r.json.username;\n"
    "      localStorage.setItem('zdb_token', state.token); enterApp();\n"
    "    } else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function doLogin() {\n"
    "  var u = document.getElementById('a-user').value.trim();\n"
    "  var p = document.getElementById('a-pass').value;\n"
    "  api('POST', '/admin/login', { username: u, password: p }).then(function (r) {\n"
    "    if (r.status === 200 && r.json && r.json.token) {\n"
    "      state.token = r.json.token; state.user = r.json.username;\n"
    "      localStorage.setItem('zdb_token', state.token); enterApp();\n"
    "    } else { setError(failText(r)); }\n"
    "  });\n"
    "}\n"
    "function logout() {\n"
    "  api('POST', '/admin/logout').then(function () {\n"
    "    state.token = ''; state.user = '';\n"
    "    localStorage.removeItem('zdb_token');\n"
    "    show('auth'); renderLogin();\n"
    "  });\n"
    "}\n"
    "function failText(r) { return r.json && r.json.error ? r.json.error : ('HTTP ' + r.status); }\n"
    "function enterApp() {\n"
    "  show('app');\n"
    "  document.getElementById('whoami').textContent = 'Signed in as ' + state.user;\n"
    "  renderNav(); load('overview');\n"
    "}\n"
    "function renderNav() {\n"
    "  var nav = document.getElementById('section-nav');\n"
    "  nav.innerHTML = SECTIONS.map(function (s) {\n"
    "    return '<a href=\"#\" data-k=\"' + s[0] + '\" class=\"nav-link\" onclick=\"load(\\'' + s[0] + '\\');return false;\">' + s[1] + '</a>';\n"
    "  }).join('');\n"
    "}\n"
    "function load(key) {\n"
    "  var links = document.querySelectorAll('#section-nav .nav-link');\n"
    "  for (var i = 0; i < links.length; i++) links[i].classList.remove('active');\n"
    "  var lk = document.querySelector('#section-nav [data-k=\\\"' + key + '\\\"]');\n"
    "  if (lk) lk.classList.add('active');\n"
    "  window['render' + key.charAt(0).toUpperCase() + key.slice(1)]();\n"
    "}\n"
    "function table(columns, rows) {\n"
    "  var head = '<tr>' + columns.map(function (c) { return '<th>' + c + '</th>'; }).join('') + '</tr>';\n"
    "  var body = rows.map(function (r) {\n"
    "    return '<tr>' + r.map(function (c) { return '<td>' + esc(c) + '</td>'; }).join('') + '</tr>';\n"
    "  }).join('');\n"
    "  return '<table class=\"table table-striped table-bordered align-middle\"><thead>' + head + '</thead><tbody>' + body + '</tbody></table>';\n"
    "}\n"
    "function esc(s) { return String(s === undefined || s === null ? '' : s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\\\"/g,'&quot;'); }\n"
    "function err(msg) { return '<div class=\"alert alert-danger\">' + esc(msg) + '</div>'; }\n"
    "function ok(msg) { return '<div class=\"alert alert-success\">' + esc(msg) + '</div>'; }\n"
    "function renderOverview() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/status').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    c.innerHTML =\n"
    "      '<h5>Overview</h5>' +\n"
    "      '<dl class=\"row\">' +\n"
    "      '<dt class=\"col-sm-3\">Service</dt><dd class=\"col-sm-9\">' + esc(r.json.service) + '</dd>' +\n"
    "      '<dt class=\"col-sm-3\">Version</dt><dd class=\"col-sm-9\">' + esc(r.json.version) + '</dd>' +\n"
    "      '</dl>';\n"
    "  });\n"
    "}\n"
    "function renderDatabases() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Databases</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/databases').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (d) { return [d.name, d.replication_factor]; });\n"
    "    c.innerHTML = table(['Name', 'Replication factor'], rows) +\n"
    "      '<div class=\"card\"><div class=\"card-body\"><h6>Create database</h6>' +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"db-name\" class=\"form-control\" placeholder=\"name\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"db-rf\" class=\"form-control\" type=\"number\" value=\"1\" min=\"1\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createDb()\">Create</button></div></div></div></div>' +\n"
    "      '<h6 class=\"mt-3\">Delete database</h6><div class=\"row g-2\"><div class=\"col\"><input id=\"db-del\" class=\"form-control\" placeholder=\"name\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-danger\" onclick=\"delDb()\">Delete</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function createDb() { mutate('POST', '/admin/databases', { name: id('db-name'), replication_factor: parseInt(id('db-rf'), 10) }, renderDatabases); }\n"
    "function delDb() { mutate('DELETE', '/admin/databases/' + id('db-del'), undefined, renderDatabases); }\n"
    "function renderGroups() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Groups</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/groups').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (g) { return [g.name, g.bit_position]; });\n"
    "    c.innerHTML = table(['Name', 'Bit'], rows) +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"grp-name\" class=\"form-control\" placeholder=\"group name\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"mutate(\\'POST\\', \\'/admin/groups\\', { name: id(\\'grp-name\\') }, renderGroups)\">Create</button></div>' +\n"
    "      '<div class=\"col\"><input id=\"grp-del\" class=\"form-control\" placeholder=\"group name\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-danger\" onclick=\"mutate(\\'DELETE\\', \\'/admin/groups/\\' + id(\\'grp-del\\'), undefined, renderGroups)\">Delete</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function renderUsers() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Users</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/users').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (u) { return [u.name, u.groups]; });\n"
    "    c.innerHTML = table(['Name', 'Groups'], rows) +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"usr-name\" class=\"form-control\" placeholder=\"username\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"usr-groups\" class=\"form-control\" placeholder=\"group mask (e.g. 1)\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createUser()\">Create</button></div>' +\n"
    "      '<div class=\"col\"><input id=\"usr-del\" class=\"form-control\" placeholder=\"username\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-danger\" onclick=\"mutate(\\'DELETE\\', \\'/admin/users/\\' + id(\\'usr-del\\'), undefined, renderUsers)\">Delete</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function createUser() { mutate('POST', '/admin/users', { name: id('usr-name'), groups: id('usr-groups') }, renderUsers); }\n"
    "function renderPartitions() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Partitions</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/partitions').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (p) { return [p.database, p.name, p.create_mask, p.update_mask, p.read_mask, p.delete_mask]; });\n"
    "    c.innerHTML = table(['Database', 'Name', 'Create', 'Update', 'Read', 'Delete'], rows) +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"pt-db\" class=\"form-control\" placeholder=\"database\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"pt-name\" class=\"form-control\" placeholder=\"partition\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"createPartition()\">Create (allow-all)</button></div>' +\n"
    "      '<div class=\"col\"><input id=\"pt-del-db\" class=\"form-control\" placeholder=\"database\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"pt-del\" class=\"form-control\" placeholder=\"partition\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-danger\" onclick=\"mutate(\\'DELETE\\', \\'/admin/partitions/\\' + id(\\'pt-del-db\\') + \\'/\\' + id(\\'pt-del\\'), undefined, renderPartitions)\">Delete</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function createPartition() {\n"
    "  mutate('POST', '/admin/partitions', { database: id('pt-db'), name: id('pt-name'), create_mask: '0', update_mask: '0', read_mask: '0', delete_mask: '0' }, renderPartitions);\n"
    "}\n"
    "function renderKeyspaces() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Keyspaces</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/keyspaces').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (k) { return [k.database, k.partition, k.name]; });\n"
    "    c.innerHTML = table(['Database', 'Partition', 'Keyspace'], rows);\n"
    "  });\n"
    "}\n"
    "function renderSettings() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Settings</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/settings').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    var rows = r.json.map(function (s) { return [s.name, JSON.stringify(s.value)]; });\n"
    "    c.innerHTML = table(['Name', 'Value'], rows) +\n"
    "      '<div class=\"row g-2\"><div class=\"col\"><input id=\"set-name\" class=\"form-control\" placeholder=\"setting name\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"set-val\" class=\"form-control\" placeholder=\"JSON value\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"setSetting()\">Set</button></div>' +\n"
    "      '<div class=\"col\"><input id=\"set-del\" class=\"form-control\" placeholder=\"setting name\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-danger\" onclick=\"mutate(\\'DELETE\\', \\'/admin/settings/\\' + id(\\'set-del\\'), undefined, renderSettings)\">Delete</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function setSetting() {\n"
    "  var v = id('set-val'); var body = v; try { body = JSON.parse(v); } catch (e) {}\n"
    "  mutate('POST', '/admin/settings/' + id('set-name'), body, renderSettings);\n"
    "}\n"
    "function renderData() {\n"
    "  document.getElementById('content').innerHTML =\n"
    "    '<h5>Data</h5>' +\n"
    "    '<div class=\"row g-2 mb-2\">' +\n"
    "    '<div class=\"col-2\"><select id=\"dt-op\" class=\"form-select\"><option>get</option><option>put</option><option>rm</option><option>all</option><option>ids</option><option>query</option></select></div>' +\n"
    "    '<div class=\"col\"><input id=\"dt-path\" class=\"form-control\" placeholder=\"database/partition/keyspace[/id]\"></div>' +\n"
    "    '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"dataOp()\">Run</button></div></div>' +\n"
    "    '<textarea id=\"dt-body\" class=\"form-control mb-2\" rows=\"4\" placeholder=\"JSON body (put: document, query/all/ids: filter object or {filters:[...]})\"></textarea>' +\n"
    "    '<pre id=\"dt-out\" class=\"bg-light border rounded p-2\"></pre>';\n"
    "}\n"
    "function dataOp() {\n"
    "  var op = document.getElementById('dt-op').value;\n"
    "  var path = document.getElementById('dt-path').value.trim();\n"
    "  var raw = document.getElementById('dt-body').value.trim();\n"
    "  var body = raw ? JSON.parse(raw) : undefined;\n"
    "  var seg = path.split('/');\n"
    "  var reqPath = '/data/' + path;\n"
    "  if (op === 'get') { api('GET', reqPath).then(showData); }\n"
    "  else if (op === 'rm') { api('DELETE', reqPath).then(showData); }\n"
    "  else if (op === 'put') { api('PUT', reqPath, body).then(showData); }\n"
    "  else { api('POST', reqPath + '/' + op, body).then(showData); }\n"
    "}\n"
    "function showData(r) {\n"
    "  var out = document.getElementById('dt-out');\n"
    "  out.textContent = (r.json !== null ? JSON.stringify(r.json, null, 2) : r.text);\n"
    "  out.classList.remove('border-danger');\n"
    "  if (r.status >= 400) out.classList.add('border-danger');\n"
    "}\n"
    "function renderCluster() {\n"
    "  var c = document.getElementById('content');\n"
    "  c.innerHTML = '<h5>Cluster</h5><div class=\"spinner-border\"></div>';\n"
    "  api('GET', '/admin/cluster').then(function (r) {\n"
    "    if (!r.json) { c.innerHTML = err(failText(r)); return; }\n"
    "    c.innerHTML = '<pre class=\"bg-light border rounded p-2\">' + esc(JSON.stringify(r.json, null, 2)) + '</pre>' +\n"
    "      '<h6>Join a node</h6><div class=\"row g-2\"><div class=\"col\"><input id=\"join-addr\" class=\"form-control\" placeholder=\"127.0.0.1\"></div>' +\n"
    "      '<div class=\"col\"><input id=\"join-port\" class=\"form-control\" type=\"number\" placeholder=\"port\"></div>' +\n"
    "      '<div class=\"col-auto\"><button class=\"btn btn-primary\" onclick=\"joinNode()\">Join</button></div></div>';\n"
    "  });\n"
    "}\n"
    "function joinNode() {\n"
    "  mutate('POST', '/admin/join', { addr: id('join-addr'), port: parseInt(id('join-port'), 10) }, renderCluster);\n"
    "}\n"
    "function id(n) { return document.getElementById(n).value; }\n"
    "function mutate(method, path, body, after) {\n"
    "  api(method, path, body).then(function (r) { after(); });\n"
    "}\n"
    "checkState();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

static bool console_handler(const zdb_http_request *req, zdb_http_response *res)
{
    (void)req;
    res->status = 200;
    res->content_type = "text/html; charset=utf-8";
    res->body = strdup(console_html);
    res->body_len = strlen(console_html);
    return true;
}

bool zdb_admin_console_register(zdb_http_server *srv)
{
    if (!srv) {
        return false;
    }
    return zdb_http_add_handler(srv, "GET", "/admin", console_handler);
}
